[theme]

# Primary accent for interactive elements
primaryColor = '#808080'

# Background color for the main content area
backgroundColor = '#013220'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#052e01'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif I sans serif I monospace)
# Default: "sans serif"
font = "sans serif"